volumes:
  redis_data:
  gradle_cache25:
services:
  redis:
    container_name: redis
    image: redis:8.2-alpine@sha256:94589dc90eb8b7eb920f3a9a6d85657e73fd20db61410719500b9c5ba0548d9a
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GRADLE_USER_HOME: /home/gradle/.gradle
    image: smart-links:latest
    ports:
      - "8080:8080"
    volumes:
      - gradle_cache25:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    restart: always
    depends_on:
      - redis
