version: '3.9'

volumes:
  redis_data:
  gradle_cache17:
services:
  redis:
    container_name: redis
    image: docker.io/bitnami/redis:7.0
    environment:
      REDIS_PASSWORD: password
      REDIS_PORT_NUMBER: 6379
    ports:
      - "6379:6379"
    volumes:
      - 'redis_data:/bitnami/redis/data'
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GRADLE_USER_HOME: /home/gradle/.gradle
    image: smart-links:latest
    ports:
      - "8080:8080"
    volumes:
      # Монтирование тома для кэширования Gradle-зависимостей
      - gradle_cache17:/home/gradle/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    depends_on:
      - redis
