spring:
  application:
    name: SmartLinks
  data:
    redis:
      host: localhost
      port: 6379
      password: password
springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    url: /v3/api-docs
    use-root-path: true
server:
  port: 8080