apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smart-links-ingress
spec:
  rules:
    - host: smart-links.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smart-links-service
                port:
                  number: 80
