name: OpenSSF Scorecard

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: "17 4 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    name: OSSF Scorecards
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - name: Analyze
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: scorecard-results.json
          results_format: json
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          publish_results: false
      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: openssf-scorecard
          path: scorecard-results.json
          if-no-files-found: error
